library(data.table)
root <- normalizePath(getwd(), winslash='/', mustWork=FALSE)
ms <- fread(file.path(root,'outputs/tables/csv/econometric_model_summary.csv'))
comp <- fread(file.path(root,'outputs/tables/csv/model_sample_composition.csv'))
stopifnot(all(c('income_level','future_growth','growth_volatility') %in% unique(ms$model)))
stopifnot(all(ms$nobs > 100))
stopifnot(all(is.finite(ms$estimate)))
stopifnot(comp$countries[1] >= 20)
stopifnot(file.exists(file.path(root,'docs/ECONOMETRIC_MODEL_AUDIT.md')))
