library(data.table)
root <- normalizePath(getwd(), winslash='/', mustWork=FALSE)
ps <- fread(file.path(root,'outputs/tables/csv/product_space_network_diagnostics.csv'))
val <- function(m) as.numeric(ps[metric==m, value][1])
stopifnot(val('analytical_positive_edges') > val('visual_edges'))
stopifnot(val('visual_edges') >= 500)
stopifnot(val('diag_max_abs') == 0)
stopifnot(val('symmetry_max_abs_diff') < 1e-10)
edges <- fread(file.path(root,'outputs/networks/product_space_visual_edges.csv'), colClasses=list(character=c('from','to')))
stopifnot(!anyDuplicated(edges[, .(pmin(from,to), pmax(from,to))]))
