library(data.table)
root <- normalizePath(getwd(), winslash='/', mustWork=FALSE)
opp <- fread(file.path(root,'outputs/tables/csv/bolivia_opportunities_revised.csv'), colClasses=list(character='product_code'))
top40 <- fread(file.path(root,'outputs/tables/csv/bolivia_top40_economic_review.csv'), colClasses=list(character='product_code'))
stopifnot(nrow(opp) == 1138)
stopifnot(opp[eligible==TRUE, .N] > 500)
stopifnot(opp[relative_category=='Strategic bets', .N] > 0)
stopifnot(all(grepl('^[0-9]{4}$', opp$product_code)))
stopifnot(all(c('feasibility_score','transformation_score','relative_category') %in% names(opp)))
stopifnot(nrow(top40) >= 30)
stopifnot(all(is.finite(top40$density)))
