options(stringsAsFactors = FALSE)
root <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
p <- function(...) file.path(root, ...)
for (d in c("docs","outputs/tables/csv","outputs/reports")) if (!dir.exists(p(d))) dir.create(p(d), recursive=TRUE)
library(data.table)
expected <- c("README.md","docs/DATA_INVENTORY.csv","docs/DATA_INVENTORY.md","docs/DATA_FEASIBILITY_REPORT.md","docs/METHODOLOGY.md","docs/EMPIRICAL_STRATEGY.md","docs/DATA_DICTIONARY.md","docs/REPRODUCIBILITY.md","docs/LIMITATIONS.md","docs/PROJECT_LOG.md","paper/main.qmd","paper/main.html","paper/main.pdf","paper/policy_brief.qmd","paper/policy_brief.html","paper/abstract.md","paper/executive_summary.md","paper/key_findings.md","dashboard/app.R","outputs/reports/VALIDATION_REPORT.html","outputs/tables/xlsx/bolivia_opportunities.xlsx","outputs/figures/png/bolivia_product_space.png","outputs/figures/png/bolivia_density_pci.png","outputs/figures/png/eci_latin_america_trends.png","outputs/figures/png/complexity_income.png","R/99_run_all.R")
ignore_lines <- if (file.exists(p(".gitignore"))) readLines(p(".gitignore"), warn=FALSE) else character()
is_ignored <- function(rel){ rel2 <- gsub("\\\\","/",rel); any(vapply(ignore_lines, function(rule){ rule <- trimws(rule); if(rule==""||startsWith(rule,"#")) return(FALSE); rule <- gsub("\\\\","/",rule); if(endsWith(rule,"/")) return(startsWith(rel2,rule)); if(grepl("*", rule, fixed=TRUE)){ rx <- paste0("^", gsub("\\*",".*",gsub("\\.","\\\\.",rule)), "$"); return(grepl(rx, rel2))}; rel2==rule || startsWith(rel2,paste0(rule,"/"))}, logical(1))) }
can_open <- function(file){ if(!file.exists(file)) return(FALSE); ext <- tolower(tools::file_ext(file)); tryCatch({ if(ext %in% c("md","qmd","R","yml","yaml","csv","txt","html","cff")){ readLines(file,n=2,warn=FALSE); TRUE } else if(ext=="xlsx"){ openxlsx::getSheetNames(file); TRUE } else if(ext=="png"){ con <- file(file,"rb"); on.exit(close(con), add=TRUE); identical(readBin(con,"raw",8), as.raw(c(0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a))) } else file.info(file)$size>0 }, error=function(e) FALSE) }
contains_results <- function(file){ if(!file.exists(file)||file.info(file)$size==0) return(FALSE); ext <- tolower(tools::file_ext(file)); if(ext %in% c("png","pdf","xlsx")) return(TRUE); txt <- tryCatch(paste(readLines(file,n=80,warn=FALSE), collapse=" "), error=function(e) ""); grepl("Bolivia|ECI|RCA|2023|Opportunity|Validation|HHI|Product Space|4,582|6497429", txt, ignore.case=TRUE) }
deliv <- rbindlist(lapply(expected, function(rel){ f <- p(rel); ex <- file.exists(f); info <- if(ex) file.info(f) else NULL; size <- if(ex) info$size else NA_real_; data.table(expected_path=rel, exists=ex, size_bytes=size, modified_time=if(ex) as.character(info$mtime) else NA_character_, empty=ex&&size==0, opens_correctly=can_open(f), contains_real_results=contains_results(f), gitignored=is_ignored(rel), publish_to_github=ex&&!is_ignored(rel)&&!grepl("data/processed|logs/|outputs/models", rel), action_needed=if(!ex) "create or document why unavailable" else if(is_ignored(rel)&&!grepl("main.pdf",rel)) "review gitignore" else if(ex&&size==0) "populate" else "none") }))
fwrite(deliv, p("docs/DELIVERABLES_AUDIT.csv"))
counts <- data.table(metric=c("png_figures","pdf_figures","svg_figures","csv_tables","xlsx_tables","html_tables","saved_models","dashboard_files","tests"), count=c(length(list.files(p("outputs/figures/png"),"\\.png$",full.names=TRUE)), length(list.files(p("outputs/figures/pdf"),"\\.pdf$",full.names=TRUE)), length(list.files(p("outputs/figures/svg"),"\\.svg$",full.names=TRUE)), length(list.files(p("outputs/tables/csv"),"\\.csv$",full.names=TRUE)), length(list.files(p("outputs/tables/xlsx"),"\\.xlsx$",full.names=TRUE)), length(list.files(p("outputs/tables/html"),"\\.html$|\\.txt$",full.names=TRUE)), length(list.files(p("outputs/models"),full.names=TRUE)), length(list.files(p("dashboard"),recursive=TRUE,full.names=TRUE)), length(list.files(p("tests"),"\\.R$",full.names=TRUE))))
md <- c("# Deliverables Audit", "", "Physical verification of announced deliverables. No raw-data folders were rescanned.", "", paste0("Expected deliverables: ", nrow(deliv)), paste0("Existing deliverables: ", deliv[exists==TRUE,.N]), paste0("Missing deliverables: ", deliv[exists==FALSE,.N]), "", "## Counts", "", paste0("- ", counts$metric, ": ", counts$count), "", "## Action Needed", "", if(nrow(deliv[action_needed!='none'])==0) "- None" else paste0("- ", deliv[action_needed!='none']$expected_path, ": ", deliv[action_needed!='none']$action_needed))
writeLines(md, p("docs/DELIVERABLES_AUDIT.md"), useBytes=TRUE)
writeLines(c("# GitHub File Policy", "", "## Publish", "README, code, config examples, documentation, small final tables, final figures, HTML paper and policy brief, dashboard code, validation reports, tests, and sample data.", "", "## Exclude", "Raw data, large processed caches, logs, local path configuration, model RDS files, package libraries, temporary files, and machine-specific artifacts.", "", "## Reconstruct Excluded Files", "Copy `config/paths.example.yml` to ignored `config/paths.local.yml`, edit local paths, then run `Rscript R/99_run_all.R`."), p("docs/GITHUB_FILE_POLICY.md"), useBytes=TRUE)
cat("Stage 1 audit complete\n")