options(stringsAsFactors=FALSE, scipen=999)
root <- normalizePath(getwd(), winslash="/", mustWork=TRUE); p <- function(...) file.path(root,...)
for(d in c("docs","outputs/tables/csv","outputs/tables/xlsx","outputs/networks")) if(!dir.exists(p(d))) dir.create(p(d), recursive=TRUE)
library(data.table); library(Matrix); library(openxlsx)
trade <- as.data.table(arrow::read_parquet(p("data/processed/trade_country_product_year.parquet")))
cy <- fread(p("outputs/tables/csv/country_year_indicators.csv")); py <- fread(p("outputs/tables/csv/product_year_indicators.csv")); panel <- fread(p("data/processed/country_year_panel.csv")); opp <- fread(p("outputs/tables/csv/bolivia_opportunities.csv")); prod <- fread(p("data/processed/product_dictionary.csv"))
normalize_hs4 <- function(x) {
  x <- trimws(as.character(x))
  ok <- !is.na(x) & grepl("^[0-9]+$", x) & nchar(x) < 4
  x[ok] <- sprintf("%04d", as.integer(x[ok]))
  x
}
trade[, product_code := normalize_hs4(product_code)]
py[, product_code := normalize_hs4(product_code)]
opp[, product_code := normalize_hs4(product_code)]
if ("product_code" %in% names(prod)) prod[, product_code := normalize_hs4(product_code)]
if ("product_hs92_code" %in% names(prod)) prod[, product_hs92_code := normalize_hs4(product_hs92_code)]
lac <- c("ARG","BOL","BRA","CHL","COL","CRI","ECU","SLV","GTM","HND","MEX","NIC","PAN","PRY","PER","DOM","URY","VEN","CUB","JAM","TTO","BRB","BHS","BLZ","GUY","SUR","HTI")
latest_year <- max(trade[country_code=="BOL" & total_country_exports>0, year], na.rm=TRUE)
# Base integrity
base <- data.table(metric=c("rows","countries","products","min_year","max_year","bolivia_latest_year","unique_keys","negative_exports","duplicate_keys","missing_rca","invalid_country_codes","invalid_product_codes","zero_export_country_year_rows"), value=as.character(c(nrow(trade), uniqueN(trade$country_code), uniqueN(trade$product_code), min(trade$year), max(trade$year), max(trade[country_code=="BOL",year]), nrow(unique(trade[,.(country_code,product_code,year)]))==nrow(trade), sum(trade$export_value<0,na.rm=TRUE), anyDuplicated(trade[,.(country_code,product_code,year)]), sum(!is.finite(trade$rca)), sum(!grepl("^[A-Z]{3}$", trade$country_code)), sum(!grepl("^[0-9]{4}$", as.character(trade$product_code))), trade[total_country_exports==0,.N])) )
fwrite(base, p("outputs/tables/csv/data_integrity_summary.csv"))
# RCA validation sample
countries <- intersect(c("BOL","BRA","MEX","CHL","KOR"), unique(trade$country_code)); years <- as.integer(intersect(c(min(trade$year), 2009, max(trade$year)), unique(trade$year)))
prod_pool <- trade[country_code %in% countries & year %in% years, .(x=sum(export_value)), by=product_code][order(-x)]
products <- unique(c(head(prod_pool$product_code,3), tail(prod_pool[x>0]$product_code,2)))
rs <- trade[country_code %in% countries & year %in% years & product_code %in% products]
rs[, rca_manual := fifelse(total_country_exports>0 & total_world_exports_product>0 & total_world_exports>0, (export_value/total_country_exports)/(total_world_exports_product/total_world_exports), 0)]
rs[!is.finite(rca_manual), rca_manual:=0]; rs[, abs_diff:=abs(rca-rca_manual)]; rs[, mcp_manual:=as.integer(rca_manual>=1)]
fwrite(rs[,.(country_code,year,product_code,export_value,total_country_exports,total_world_exports_product,total_world_exports,rca_pipeline=rca,rca_manual,abs_diff,mcp,mcp_manual)], p("outputs/tables/csv/rca_validation_sample.csv"))
# ECI PCI validation
eci <- fread(p("data/processed/country_year_complexity.csv")); pci <- fread(p("data/processed/product_year_complexity.csv"))
pci[, product_code := normalize_hs4(product_code)]
eci_val <- eci[,.(countries=.N,mean_eci=mean(eci,na.rm=TRUE),sd_eci=sd(eci,na.rm=TRUE),min_eci=min(eci,na.rm=TRUE),max_eci=max(eci,na.rm=TRUE),infinite=sum(!is.finite(eci)),zero_diversity=sum(diversity_complexity<=0,na.rm=TRUE)),by=year]
pci_val <- pci[,.(products=.N,mean_pci=mean(pci,na.rm=TRUE),sd_pci=sd(pci,na.rm=TRUE),min_pci=min(pci,na.rm=TRUE),max_pci=max(pci,na.rm=TRUE),infinite=sum(!is.finite(pci)),zero_ubiquity=sum(ubiquity_complexity<=0,na.rm=TRUE)),by=year]
fwrite(eci_val,p("outputs/tables/csv/eci_validation_summary.csv")); fwrite(pci_val,p("outputs/tables/csv/pci_validation_summary.csv"))
writeLines(c("# ECI And PCI Technical Validation","","ECI is recomputed year by year from the binary RCA matrix using the country-side normalized reflection matrix `D_c^-1 M D_p^-1 M'`. The second eigenvector is selected, standardized within year, and sign-oriented to correlate positively with diversity.","","PCI is a projected product index: product values are obtained by projecting country ECI through the product side of the RCA matrix and standardizing within year. It is not a separate product-side eigen-decomposition.","","Because ECI and PCI are standardized separately each year, they support relative within-year comparisons and rankings. Changes over time should be interpreted as changes in relative position, not absolute capability accumulation.","",paste0("Max absolute annual ECI mean: ",signif(max(abs(eci_val$mean_eci)),3)),paste0("Annual ECI sd range: ",round(min(eci_val$sd_eci),3),"-",round(max(eci_val$sd_eci),3)),paste0("Annual PCI sd range: ",round(min(pci_val$sd_pci),3),"-",round(max(pci_val$sd_pci),3))), p("docs/ECI_PCI_TECHNICAL_VALIDATION.md"), useBytes=TRUE)
# Bolivia 2023 validation
bol_trade <- trade[country_code=="BOL" & year==latest_year]; bol_cy <- cy[country_code=="BOL" & year==latest_year]; regional <- cy[region=="Latin America and Caribbean" & year==latest_year]
hhi_calc <- sum((bol_trade$export_value/sum(bol_trade$export_value))^2, na.rm=TRUE); prim <- sum(bol_trade[product_section %in% c("Animal products","Vegetable products","Fats and oils","Foodstuffs","Minerals"), export_value],na.rm=TRUE)/sum(bol_trade$export_value)
rank_hhi <- regional[order(hhi)][,rank_low_to_high:=.I][country_code=="BOL",rank_low_to_high]; pct_hhi <- mean(regional$hhi <= bol_cy$hhi, na.rm=TRUE)
fwrite(regional[country_code %in% c("BOL","PER","CHL","PRY","ECU","COL","URY"),.(country_code,hhi,diversity,primary_share,eci)][order(-hhi)], p("outputs/tables/csv/bolivia_regional_hhi_comparison.csv"))
bol_val <- data.table(indicator=c("ECI","Diversity","HHI","Primary export share"), reported_value=c(-1.235808,82,0.1243863,0.6267532), recalculated_value=c(bol_cy$eci, bol_cy$diversity, hhi_calc, prim), definition=c("standardized country eigenvector","count of HS4 RCA>=1 products","sum of squared HS4 export shares","share of exports in primary HS sections"), numerator=c(NA, bol_trade[mcp==1,.N], NA, sum(bol_trade[product_section %in% c("Animal products","Vegetable products","Fats and oils","Foodstuffs","Minerals"), export_value])), denominator=c(NA, uniqueN(bol_trade$product_code), sum(bol_trade$export_value), sum(bol_trade$export_value)), source_processed="data/processed/trade_country_product_year.parquet", observations=c("relative within year","HS92 4-digit",paste0("regional median HHI=",round(median(regional$hhi,na.rm=TRUE),3),"; percentile=",round(pct_hhi,3),"; rank=",rank_hhi),"primary sections include agriculture, food, fats/oils, minerals"))
fwrite(bol_val,p("outputs/tables/csv/bolivia_2023_indicator_validation.csv"))
# Product Space full matrix diagnostics
mcp_dt <- unique(trade[year==latest_year & mcp==1,.(country_code,product_code)]); prods <- sort(unique(trade[year==latest_year,product_code])); ctys <- sort(unique(trade[year==latest_year,country_code])); M <- sparseMatrix(i=match(mcp_dt$country_code,ctys), j=match(mcp_dt$product_code,prods), x=1, dims=c(length(ctys),length(prods))); kp <- as.numeric(Matrix::colSums(M)); co <- as.matrix(t(M)%*%M); phi <- pmin(t(t(co)/kp), co/kp); phi[!is.finite(phi)]<-0; diag(phi)<-0; rownames(phi)<-colnames(phi)<-prods
edges <- fread(p("outputs/networks/product_space_edges.csv")); pos_edges <- which(phi>0 & upper.tri(phi), arr.ind=TRUE); analytical_edges <- data.table(from=prods[pos_edges[,1]], to=prods[pos_edges[,2]], proximity=phi[pos_edges])
fwrite(analytical_edges[order(-proximity)][1:min(.N,50000)], p("outputs/networks/product_space_analytical_edges_top50000.csv")); fwrite(edges,p("outputs/networks/product_space_visual_edges.csv"))
ps <- data.table(metric=c("year","products","countries","analytical_positive_edges","visual_edges","visual_threshold","phi_min","phi_max","diag_max_abs","symmetry_max_abs_diff","duplicate_visual_edges","visual_isolated_products"), value=as.character(c(latest_year,length(prods),length(ctys),nrow(analytical_edges),nrow(edges),0.55,min(phi),max(phi),max(abs(diag(phi))),max(abs(phi-t(phi))),anyDuplicated(edges[,.(pmin(from,to),pmax(from,to))]),length(setdiff(prods,unique(c(edges$from,edges$to)))))))
fwrite(ps,p("outputs/tables/csv/product_space_network_diagnostics.csv"))
writeLines(c("# Product Space Validation","","The analytical Product Space uses the full product-product proximity matrix for 2023. Density and Opportunity Gain are computed from this full matrix, not from the reduced 698-edge visual network.","",paste0("Full products: ",length(prods),"; countries: ",length(ctys),"; positive analytical edges: ",nrow(analytical_edges),"; visual edges: ",nrow(edges),"."),"","The 0.55 visual threshold is a legibility filter, not the computational universe."), p("docs/PRODUCT_SPACE_VALIDATION.md"), useBytes=TRUE)
# Distribution and revised opportunities
stat_row <- function(x,nm) { x <- as.numeric(x); data.table(variable=nm,min=min(x,na.rm=TRUE),p10=quantile(x,.10,na.rm=TRUE),p25=quantile(x,.25,na.rm=TRUE),median=median(x,na.rm=TRUE),p75=quantile(x,.75,na.rm=TRUE),p90=quantile(x,.90,na.rm=TRUE),max=max(x,na.rm=TRUE),mean=mean(x,na.rm=TRUE),sd=sd(x,na.rm=TRUE),missing=sum(is.na(x))) }
fwrite(rbindlist(list(stat_row(opp$density,"density"),stat_row(opp$pci_final,"pci"),stat_row(opp$opportunity_gain,"opportunity_gain"),stat_row(opp$world_market_size,"world_market_size"),stat_row(opp$demand_growth,"demand_growth"),stat_row(opp$opportunity_score,"opportunity_score"))), p("outputs/tables/csv/bolivia_density_distribution.csv"))
pct_rank <- function(x){ out<-rep(NA_real_,length(x)); ok<-is.finite(x); if(sum(ok)==1) out[ok]<-1 else if(sum(ok)>1) out[ok]<-(rank(x[ok],ties.method="average")-1)/(sum(ok)-1); out }
world_hist <- trade[year %in% ((latest_year-5):latest_year), .(world_exports=sum(export_value)), by=.(product_code,year)]; cont <- world_hist[world_exports>0,.(positive_years_last6=.N),by=product_code]; current_bol <- unique(bol_trade[mcp==1,product_code])
rev <- merge(copy(opp), cont, by="product_code", all.x=TRUE); rev[is.na(positive_years_last6),positive_years_last6:=0]; rev[, residual_code:=grepl("not elsewhere|n.e.c|n.e.s|nes|special|miscellaneous|commodities not specified|unclassified", paste(product_name,product_name_short), ignore.case=TRUE)]
market_cut <- quantile(rev$world_market_size[rev$world_market_size>0], .10, na.rm=TRUE); rev[, eligible:=!product_code %in% current_bol & world_market_size>=market_cut & positive_years_last6>=4 & !residual_code & !is.na(product_section) & product_section!="Unclassified"]
rev[,`:=`(density_pct=pct_rank(density), pci_pct=pct_rank(pci_final), opportunity_gain_pct=pct_rank(opportunity_gain), world_market_pct=pct_rank(log1p(world_market_size)), demand_growth_pct=pct_rank(demand_growth))]
score <- function(dt,w){ cols <- names(w); m<-as.matrix(dt[,..cols]); denom<-rowSums(sweep(!is.na(m),2,w,`*`)); fifelse(denom>0,rowSums(sweep(m,2,w,`*`),na.rm=TRUE)/denom,NA_real_) }
rev[, feasibility_score:=score(.SD,c(density_pct=.50,pci_pct=.15,opportunity_gain_pct=.15,world_market_pct=.10,demand_growth_pct=.10)), .SDcols=c("density_pct","pci_pct","opportunity_gain_pct","world_market_pct","demand_growth_pct")]
rev[, transformation_score:=score(.SD,c(density_pct=.25,pci_pct=.30,opportunity_gain_pct=.25,world_market_pct=.10,demand_growth_pct=.10)), .SDcols=c("density_pct","pci_pct","opportunity_gain_pct","world_market_pct","demand_growth_pct")]
rev[, absolute_classification:=opportunity_type]
rev[, relative_category:=fifelse(!eligible,"Excluded from relative universe",fifelse(density_pct>=.75 & pci_pct>=.50 & world_market_pct>=.50,"Quick wins",fifelse(opportunity_gain_pct>=.75 & pci_pct>=.75 & density_pct>=.40 & density_pct<.75,"Strategic bets",fifelse(density_pct>=.75 & pci_pct<.50,"Incremental extensions",fifelse(pci_pct>=.75 & opportunity_gain_pct>=.75 & density_pct<.40,"Transformational long shots",fifelse(density_pct<.50 & pci_pct<.50 & opportunity_gain_pct<.50,"Low-priority products","Middle-range candidates"))))))]
fwrite(rev,p("outputs/tables/csv/bolivia_opportunities_revised.csv")); sector <- rev[eligible==TRUE,.(candidates=.N,median_density=median(density),median_pci=median(pci_final),median_feasibility=median(feasibility_score),median_transformation=median(transformation_score)),by=product_section][order(-candidates)]; meth <- data.table(note=c("Relative classification is computed within Bolivia's eligible opportunity universe.","Eligible products exclude current RCA, marginal markets, discontinuous products, residual descriptions, and unclassified products.","Scores use percentile-normalized components; market size is log-transformed before ranking.","Absolute classification is retained unchanged."))
openxlsx::write.xlsx(list(all_candidates=rev, absolute_classification=rev[,.N,by=absolute_classification], relative_classification=rev[,.N,by=relative_category], feasibility_top20=head(rev[eligible==TRUE][order(-feasibility_score)],20), transformation_top20=head(rev[eligible==TRUE][order(-transformation_score)],20), quick_wins=rev[relative_category=="Quick wins"][order(-feasibility_score)], strategic_bets=rev[relative_category=="Strategic bets"][order(-transformation_score)], incremental_extensions=rev[relative_category=="Incremental extensions"][order(-feasibility_score)], long_shots=rev[relative_category=="Transformational long shots"][order(-transformation_score)], sector_summary=sector, methodology=meth), p("outputs/tables/xlsx/bolivia_opportunities_revised.xlsx"), overwrite=TRUE)
top40 <- unique(rbind(head(rev[eligible==TRUE][order(-feasibility_score)],20),head(rev[eligible==TRUE][order(-transformation_score)],20),fill=TRUE),by="product_code")[1:min(.N,40)]
top40[, review_order := .I]
bol_rca <- bol_trade[, .(product_code, current_rca=rca)]
top40 <- merge(top40, bol_rca, by="product_code", all.x=TRUE, sort=FALSE)
top40[is.na(current_rca), current_rca := 0]
setorder(top40, review_order)
top40[, economic_interpretation:=paste0("HS section: ",product_section,"; ",ifelse(density_pct>=.75,"nearer to current RCA basket",ifelse(density_pct<.40,"distant from current RCA basket","intermediate proximity")),"; ",ifelse(pci_pct>=.75,"high relative complexity",ifelse(pci_pct<.5,"below-median relative complexity","moderate relative complexity")),".")]; top40[, data_warning:=fifelse(residual_code,"residual description",fifelse(positive_years_last6<6,"not present in all last six world-market years","none"))]
fwrite(top40[,.(product_code,product_description=product_name,sector=product_section,current_rca,density,pci=pci_final,opportunity_gain,world_market_size,demand_growth,feasibility_score,transformation_score,relative_category,economic_interpretation,data_warning)], p("outputs/tables/csv/bolivia_top40_economic_review.csv"))
writeLines(c("# Bolivia Opportunity Audit","",paste0("Original candidates: ",nrow(opp),". Absolute counts: ",paste(opp[,paste(opportunity_type,.N,sep='=')],collapse=', '),"."),paste0("Eligible relative universe: ",rev[eligible==TRUE,.N]," products."),"","The strict absolute result is preserved. The revised workbook adds a relative Bolivia-specific classification for feasibility studies without changing results for attractiveness."), p("docs/BOLIVIA_OPPORTUNITY_AUDIT.md"), useBytes=TRUE)
cat("Stage 2 validation complete\n")
