library(data.table)
root <- normalizePath(getwd(), winslash='/', mustWork=TRUE)
trade <- fread(file.path(root,'data/sample/trade_sample.csv'), colClasses=list(character='product_code'))
cy <- fread(file.path(root,'data/sample/country_year_sample.csv'))
opp <- fread(file.path(root,'data/sample/bolivia_opportunity_sample.csv'), colClasses=list(character='product_code'))
summary_lines <- c('# Demo Report','',paste0('- Trade sample rows: ', nrow(trade)),paste0('- Country-year sample rows: ', nrow(cy)),paste0('- Opportunity sample rows: ', nrow(opp)),paste0('- Bolivia sample years: ', paste(sort(unique(cy[country_code=='BOL', year])), collapse=', ')),paste0('- Top sample opportunity: ', opp[1, product_code], ' ', opp[1, product_name_short]))
dir.create(file.path(root,'outputs/reports'), recursive=TRUE, showWarnings=FALSE)
writeLines(summary_lines, file.path(root,'outputs/reports/DEMO_REPORT.md'), useBytes=TRUE)
cat(paste(summary_lines, collapse='\n'))
